### ISSUE TITLE
How to implement Listview infinite loading(scrolling) while using the library?

### ISSUE THREAD

**Issue by ibmkhd** [flavienlaurent/poppyview#2]
I want to use the library and at the same time allow the Listview to load data infinitely,
when i reimplement the listview setOnScrollListener-onScroll to load data infinitely the poppyview functionality stopped working.

Is there a way to implement infinite loading while keep the poppyview functionality.

-Thanks

**Comment by flavienlaurent** [comment]
Now, you can passed a listener when creating the poppyview. See 7feb7d5f1dffee4d935dd35caff91c357d93480d

**Comment by ibmkhd** [comment]
Thanks a lot.
